/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 client/public/logopovattina.glb -o client/src/components/sections/Logopovattina.tsx -r client/public 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF, Center } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['<Path>002']: THREE.Mesh
  }
  materials: {
    SVGMat: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/logopovattina.glb') as GLTFResult
  const groupRef = useRef<THREE.Group>(null)

  // Rotate slowly on the Y axis
  useFrame((state, delta) => {
    if (groupRef.current) {
      groupRef.current.rotation.y += delta * 0.4 
    }
  })

  // We wrap the mesh in <Center> so that it centers itself perfectly at the local origin.
  // This ensures the parent <group> rotates exactly around the center of the logo.
  // Reduced scale so it stays completely visible and isn't cut off
  return (
    <group ref={groupRef} {...props} dispose={null} scale={0.12}>
      <Center>
        <mesh geometry={nodes['<Path>002'].geometry} rotation={[Math.PI / 2, 0, 0]}>
           <meshStandardMaterial color="#ffffff" roughness={0.3} metalness={0.8} side={THREE.DoubleSide} />
        </mesh>
      </Center>
    </group>
  )
}

useGLTF.preload('/logopovattina.glb')
