/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 client/public/logopovattina.glb -o client/src/components/sections/Logopovattina.tsx -r client/public 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['<Path>002']: THREE.Mesh
  }
  materials: {
    SVGMat: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/logopovattina.glb') as GLTFResult
  const groupRef = useRef<THREE.Group>(null)

  // Rotate slowly on the Y axis
  useFrame((state, delta) => {
    if (groupRef.current) {
      groupRef.current.rotation.y += delta * 0.4 
    }
  })

  // We set rotation to show the logo from the front correctly
  return (
    <group ref={groupRef} {...props} dispose={null} scale={80} rotation={[Math.PI / 2, 0, 0]}>
      <mesh geometry={nodes['<Path>002'].geometry} rotation={[0, 0, 0]}>
         <meshStandardMaterial color="#ffffff" roughness={0.3} metalness={0.8} side={THREE.DoubleSide} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/logopovattina.glb')
