/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 client/public/logopovattina.glb -o client/src/components/sections/Logopovattina.tsx -r client/public
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useFrame, ThreeElements } from '@react-three/fiber'
import { useGLTF, Center } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['<Path>002']: THREE.Mesh
  }
  materials: {
    SVGMat: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: ThreeElements['group']) {
  const { nodes } = useGLTF('/3DFinito.glb') as GLTFResult
  const groupRef = useRef<THREE.Group>(null)

  useFrame((_state, delta) => {
    if (groupRef.current) {
      groupRef.current.rotation.y += delta * 0.4
    }
  })

  return (
    <group ref={groupRef} {...props} dispose={null} scale={5}>
      <Center>
        <mesh geometry={nodes['<Path>002'].geometry} rotation={[Math.PI / 2, 0, 0]}>
          <meshStandardMaterial color="#ffffff" roughness={0.3} metalness={0.8} side={THREE.DoubleSide} />
        </mesh>
      </Center>
    </group>
  )
}

useGLTF.preload('/3DFinito.glb')
